# name: Documentation

# on:
#   push:
#     branches:
#       - main  # Change to your default branch name if not "main"
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: write  # Needed to push to gh-pages branch

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Julia
#         uses: julia-actions/setup-julia@v2
#         with:
#           version: '1.11'  # Match your local Julia version

#       - name: Cache Julia packages
#         uses: actions/cache@v4
#         with:
#           path: ~/.julia/artifacts
#           key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

#       - name: Install dependencies
#         run: |
#           julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'

#       - name: Build and deploy docs
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: julia --project=docs docs/make.jl


name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

# Ensure that only one "Doc Preview Cleanup" workflow is force pushing at a time
concurrency:
  group: doc-preview-cleanup
  cancel-in-progress: false

jobs:
  doc-preview-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Delete preview and history + push changes
        run: |
          if [ -d "${preview_dir}" ]; then
              git config user.name "Documenter.jl"
              git config user.email "documenter@juliadocs.github.io"
              git rm -rf "${preview_dir}"
              git commit -m "delete preview"
              git branch gh-pages-new "$(echo "delete history" | git commit-tree "HEAD^{tree}")"
              git push --force origin gh-pages-new:gh-pages
          fi
        env:
          preview_dir: previews/PR${{ github.event.number }}